[package]
name = "snm_pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
regex = "1.10.4"
semver = "1.0.21"
colored = "2.1.0"
crossterm = "0.27"
snm_core = { path = "../snm_core"}

