[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "snm"
path = "src/main.rs"

[[bin]]
name = "npm"
path = "src/shim/npm.rs"

[[bin]]
name = "npx"
path = "src/shim/npx.rs"

[[bin]]
name = "pnpm"
path = "src/shim/pnpm.rs"

[[bin]]
name = "pnpx"
path = "src/shim/pnpx.rs"

[[bin]]
name = "node"
path = "src/shim/node.rs"


[dependencies]
log = "0.4.20"
anyhow = "1.0"
colored = "2.1.0"
dirs = "5.0.1"
semver = "1.0.21"
serde_json = "1.0"
dialoguer = "0.11.0"
env_logger = "0.11.2"
snm_core = { path = "../snm_core" }
snm_node = { path = "../snm_node" }
snm_package_manager = { path = "../snm_package_manager" }
snm_package_json = { path = "../snm_package_json" }
snm_current_dir = { path = "../snm_current_dir" }
snm_config = { path = "../snm_config" }
snm_utils = { path = "../snm_utils" }
snm_node_version = { path = "../snm_node_version" }
snm_download_builder = { path = "../snm_download_builder" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0.0", features = ["full"] }
clap = { version = "4.5.1", features = ["derive"] }
ansi_term = "0.12.1"
regex = "1.10.4"
glob = "0.3.1"
clap_complete = "4.5.1"
clap_complete_fig = "4.5.0"

