[package]
name = "snm_node"
version = "0.0.1-96"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.3", features = ["json", "blocking", "stream","native-tls-vendored"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
log = "0.4.20"
semver = "1.0.21"
colored = "2.1.0"
futures = "0.3"
chrono = "0.4"
sha2 = "0.10.2"
digest = "0.10.3"
dirs = "5.0.1"
anyhow = "1.0"
dialoguer = "0.11.0"
snm_core = { path = "../snm_core" }
snm_current_dir = { path = "../snm_current_dir" }
snm_utils = { path = "../snm_utils" }
snm_config = { path = "../snm_config" }
snm_node_version = { path = "../snm_node_version" }
snm_tarball = { path = "../snm_tarball" }
xz2 = {version = "0.1.7" , features = ["static"]}
tar = "0.4"
num-format = "0.4.0"
regex = "1.10.4"
async-trait = "0.1.50"
